# Generated by Django 3.2.5 on 2021-07-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_project_name_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='link_to_project',
            new_name='link',
        ),
    ]
