# Generated by Django 3.2.4 on 2021-07-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210714_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='other', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.CASCADE, related_name='Projects_in_that_category', to='website.category'),
            preserve_default=False,
        ),
    ]
