# Generated by Django 3.2.4 on 2021-07-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210720_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_why',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='for_whom',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
