# Generated by Django 3.2.4 on 2021-07-24 02:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210724_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 24, 2, 3, 48, 923405, tzinfo=utc)),
        ),
    ]
